name: deploy
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  deploy-site:
    runs-on: alpine-latest
    steps:
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
